#!/usr/bin/env bash

if [ $PWD != $DOTFILES ]; then
    echo "Not in the dotfiles repository root directory!"
    echo "[Exit with code 1]"
    exit 1
fi

branch=$(git rev-parse --abbrev-ref HEAD)
echo "On branch '$branch':"

function commit_and_push() {
    git add -A;
    git status
    read -p "Do you want to commit and push these changes? [Y/n]" -n 1 -r
    echo    
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git commit -m "this commit was created automatically"
        git push origin $branch
        git checkout master
        git checkout $branch install-scripts tmux nvim .gitignore personal scripts zsh
        git add -A
        git commit -m "automatic update due to push in other branch"
        git push origin master


    fi
}


if [ $branch = "master" ]; then
    commit_and_push
	echo "merge all to master"
elif [ $branch = "surfacebook" ]; then
    commit_and_push
	echo "merge only non setup specific stuff to master"
elif [ $branch = "surfacebook-dockin" ]; then
	echo "merge only non setup specific stuff to master"
else
	echo "Failed to match branch"
    exit 1
fi


