#!/usr/bin/env bash

while getopts 'ldh:' OPTION; do
    case "$OPTION" in
        l)
            echo "switching to laptop config..."
            branch=surfacebook
            ;;
        d)
            echo "switching to dockin config"
            branch=docking
            ;;
        h)
            echo "l = laptop setup, d = docking setup"
            ;;
    esac
done

change_stow_folders="alacritty,i3,i3status,picom"
pushd $DOTFILES
git checkout $branch
for folder in $(echo $change_stow_folders | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow -t ~ $folder
done
exit 0
