#!/usr/bin/env bash

STOW_FOLDERS="wezterm,nvim,personal,scripts,tmux,zsh,starship,nix"
pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "stow $folder"
	stow -D $folder
	stow -t ~ $folder
done

