#!/usr/bin/env bash

STOW_FOLDERS="wezterm,nvim,personal,scripts,tmux,zsh,starship"
NIX_FOLDER="/etc/nix-darwin"
pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "stow $folder"
	stow -D $folder
	stow -t ~ $folder
done

echo "stow nix"
sudo mkdir -p /etc/nix-darwin
sudo chown $(id -nu):$(id -ng) /etc/nix-darwin
stow -D nix
stow -t $NIX_FOLDER nix

